wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: huggingface
    huggingface_version: 4.21.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1655738019
    t:
      1:
      - 1
      - 11
      - 12
      - 45
      - 49
      - 55
      4: 3.9.2
      5: 0.12.18
      6: 4.21.0.dev0
      8:
      - 5
